stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker -f Plantarium/docker-compose.yml compose down
    - docker -f Plantarium/docker-compose.yml compose build
    - docker -f Plantarium/docker-compose.yml compose up -d
