stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker compose -f Plantarium/docker-compose.yml down
    - docker compose -f Plantarium/docker-compose.yml build --no-cache
    - docker compose -f Plantarium/docker-compose.yml up -d --force-recreate
