stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker compose -f Plantarium/plantarium/docker-compose.yml down
    - docker compose -f Plantarium/plantarium/docker-compose.yml build
    - docker compose -f Plantarium/plantarium/docker-compose.yml up -d