
services:
  frontend:
    build: FE
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - beds
      - plants
      - struct
      - weather
  auth:
    build: ./aServices/auth
    container_name: auth
    env_file:
      - ./aServices/auth/.env
    ports:
      - "3001:3000"        # Auth-Service extern auf :3001
    depends_on:
      - mysql

  beds:
    build: ./aServices/beds
    container_name: beds
    env_file:
      - ./aServices/beds/.env
    ports:
      - "3002:3000"        # API-Service extern auf :3002
      - "5556:5555"        # Prisma Studio (optional)
    depends_on:
      - mysql

  plants:
    build: ./aServices/plants
    container_name: plants
    env_file:
      - ./aServices/plants/.env
    ports:
      - "3004:3000"        # API-Service extern auf :3002
      - "5557:5555"        # Prisma Studio (optional)
    depends_on:
      - mysql

  struct:
    build: ./aServices/struct
    container_name: struct
    env_file:
      - ./aServices/struct/.env
    ports:
      - "3005:3000"        # API-Service extern auf :3002
      - "5558:5555"        # Prisma Studio (optional)
    depends_on:
      - mysql

  weather:
    build: ./aServices/weather
    container_name: weather
    env_file:
      - ./aServices/weather/.env
    ports:
      - "3003:3000"        # Weather-Service extern auf :3003
      - "5555:5555"        # Prisma Studio (optional)
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: plantDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plantarium
      MYSQL_DATABASE: plantarium
    ports:
      - "3307:3306"
    volumes:
      - plantarium-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

volumes:
  plantarium-data:
