
services:
  frontend:
    build: FE
    container_name: frontend
    ports:
      - "127.0.10.14:8080:3000"
    depends_on:
      - auth
      - beds
      - plants
      - struct
      - weather

  api:
    build: ./aServices/api
    container_name: api
    env_file:
      - ./aServices/api/.env
    ports:
      - "127.0.10.14:8082:3000"
    depends_on:
      - mysql

  weather:
    build: ./aServices/weather
    container_name: weather
    env_file:
      - ./aServices/weather/.env
    ports:
    - "127.0.10.14:8081:3000"        # Prisma Studio (optional)
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: plantDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plantarium
      MYSQL_DATABASE: plantarium
    ports:
      - "3307:3306"
    volumes:
      - plantarium-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

volumes:
  plantarium-data:
