version: '3.9'

services:
  frontend:
    build: FE
    container_name: frontend
    ports:
      - "127.0.10.1:8080:80"
    environment:
      - VITE_API_URL=/dev1/api
    depends_on:
      - backend

  backend:
    build: BE
    container_name: backend
    ports:
      - "127.0.10.1:8081:80"
    env_file:
      - ./BE/.env.production
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: plantDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plantarium
      MYSQL_DATABASE: plantarium
    volumes:
      - plantarium-data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

volumes:
  plantarium-data:
