events {}

http {
  server {
    listen 80;

    location /auth {
      proxy_pass http://auth:3000;
    }

    location /me/garden/beds {
      proxy_pass http://beds:3000;
    }

    location /me/garden/plants {
      proxy_pass http://plants:3000;
    }

    location /me/garden/structures {
      proxy_pass http://struct:3000;
    }
  }
}
